# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fdaf264ee3552604a2f9e92501e1d070d73bb0426b8b07d5ef13a7c3fee0adf7a67950d1a8ccbf5baf920d89cc526881f08d244245f167795413496bfbb5f17

test:
  secret_key_base: 118ade63b833475bce8c0e284faaf172fde72d87df0727492fd5dc90c1fbd75bf4595e3b03704dabf79a963f86a990b0a5046ca7174a42899da1e2fb78a87fb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
